# Generated by Django 5.2.3 on 2025-09-19 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='egasp_data',
            name='Current_City_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_city', to='home.city'),
        ),
        migrations.AddField(
            model_name='egasp_data',
            name='Current_Province_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_province', to='home.province'),
        ),
        migrations.AddField(
            model_name='egasp_data',
            name='Permanent_City_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_city', to='home.city'),
        ),
        migrations.AddField(
            model_name='egasp_data',
            name='Permanent_Province_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_province', to='home.province'),
        ),
    ]
