# Generated by Django 5.2.3 on 2025-07-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='egasp_data',
            name='Growth',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
