# Generated by Django 5.2.3 on 2025-09-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egasp_data',
            name='Clinic_Staff',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Requesting_Physician',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
