# Generated by Django 5.2.3 on 2025-07-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_egasp_data_growth'),
    ]

    operations = [
        migrations.AddField(
            model_name='egasp_data',
            name='Growth_span',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
