# Generated by Django 5.2.3 on 2025-11-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_egasp_data_current_city_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egasp_data',
            name='Treatment_Outcome_Other',
            field=models.CharField(blank=True, default='n/a', max_length=255),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Illicit_Drug_Use',
            field=models.CharField(choices=[('', ''), ('Drug Use, Current', 'Drug Use, Current'), ('Drug Use, past 30 days', 'Drug Use, past(>30 days)'), ('No Drug Use', 'No Drug Use'), ('No Answer', 'No Answer')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Treatment_Outcome',
            field=models.CharField(choices=[('', ''), ('Treatment Completed', 'Treatment Completed'), ('Partial Treatment Completed', 'Partial Treatment Completed'), ('No Treatment-patient refused', 'No Treatment-patient refused'), ('No Treatment-patient didnt come back', 'No Treatment-patient didnt come back'), ('No Answer', 'No Answer'), ('Not Treated', 'Not Treated'), ('Not Treated-referred to physician', 'Not Treated-referred to physician')], default='', max_length=100),
        ),
    ]
