# Generated by Django 5.2.3 on 2025-07-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_antibioticentry_ab_mic_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibioticentry',
            name='ab_MIC_operand',
            field=models.CharField(blank=True, choices=[('<', '<'), ('>', '>'), ('<=', '<='), ('>=', '>=')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='antibioticentry',
            name='ab_Retest_MIC_operand',
            field=models.CharField(blank=True, choices=[('<', '<'), ('>', '>'), ('<=', '<='), ('>=', '>=')], default='', max_length=4),
        ),
    ]
