# Generated by Django 5.2.3 on 2025-07-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_antibioticentry_ab_mic_operand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antibioticentry',
            name='ab_MICjoined',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
