# Generated by Django 5.2.3 on 2025-07-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_antibioticentry_ab_micjoined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egasp_data',
            name='Retested_Mic',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer')], default='', max_length=100),
        ),
    ]
