# Generated by Django 5.2.3 on 2025-07-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_egasp_data_date_accomplished_val_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egasp_data',
            name='ars_license',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
