# Generated by Django 5.2.3 on 2025-07-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_egasp_data_ars_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic_staff_details',
            name='ClinStaff_License',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
