# Generated by Django 5.2.3 on 2025-07-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_clinic_staff_details_clinstaff_license'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egasp_data',
            old_name='Validator',
            new_name='ars_Validator',
        ),
    ]
