# Generated by Django 5.2.3 on 2025-07-15 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_validator_egasp_data_ars_validator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egasp_data',
            old_name='Date_Accomplished_Val',
            new_name='Date_Validated_ARSP',
        ),
    ]
