# Generated by Django 5.2.3 on 2025-07-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_date_accomplished_val_egasp_data_date_validated_arsp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egasp_data',
            old_name='ars_Validator',
            new_name='Validator_Pers',
        ),
        migrations.AddField(
            model_name='egasp_data',
            name='val_license',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
