# Generated by Django 5.2.3 on 2025-07-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_ars_validator_egasp_data_validator_pers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egasp_data',
            old_name='Val_contact',
            new_name='val_contact',
        ),
        migrations.RenameField(
            model_name='egasp_data',
            old_name='Val_email',
            new_name='val_email',
        ),
    ]
