# Generated by Django 5.2.3 on 2025-07-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_val_contact_egasp_data_val_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic_staff_details',
            name='ClinStaff_Designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='egasp_data',
            name='ars_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='egasp_data',
            name='val_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
