# Generated by Django 5.2.3 on 2025-07-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_clinic_staff_details_clinstaff_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic_staff_details',
            name='ClinStaff_Telnum',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
