# Generated by Django 5.2.3 on 2025-07-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_clinic_staff_details_clinstaff_telnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic_staff_details',
            name='ClinStaff_EmailAdd',
        ),
        migrations.RemoveField(
            model_name='clinic_staff_details',
            name='ClinStaff_Telnum',
        ),
        migrations.RemoveField(
            model_name='egasp_data',
            name='ars_contact',
        ),
        migrations.RemoveField(
            model_name='egasp_data',
            name='ars_email',
        ),
        migrations.RemoveField(
            model_name='egasp_data',
            name='val_contact',
        ),
        migrations.RemoveField(
            model_name='egasp_data',
            name='val_email',
        ),
    ]
