# Generated by Django 5.2.3 on 2025-07-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_clinic_staff_details_clinstaff_emailadd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egasp_data',
            name='ars_designation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='ars_license',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='val_designation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='val_license',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
