# Generated by Django 5.2.3 on 2025-07-16 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_egasp_data_ars_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antibioticentry',
            name='ab_MICjoined',
        ),
    ]
