# Generated by Django 5.2.3 on 2025-07-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_clinic_staff_details_clinstaff_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egasp_data',
            name='Date_of_Entry',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
