# Generated by Django 5.2.3 on 2025-08-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_egasp_data_date_of_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egasp_data',
            name='Gender_Identity',
            field=models.CharField(choices=[('', ''), ('Male', 'Male'), ('Female', 'Female'), ('Transgender Male', 'Transgender Male'), ('Transgender Female', 'Transgender Female'), ('Other', 'Other'), ('Unknown', 'Unknown')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Nationality',
            field=models.CharField(choices=[('', ''), ('Filipino', 'Filipino'), ('Other', 'Other'), ('No Answer', 'No Answer')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Primary_Antibiotic',
            field=models.CharField(choices=[('None', 'None'), ('CRO IM 250mg', 'Ceftriaxone IM 250mg'), ('CRO IM 500mg', 'Ceftriaxone IM 500mg'), ('CRO IM 1g', 'Ceftriaxone IM 1g'), ('CFM PO 400mg', 'Cefixime PO 400mg'), ('CFM PO 800mg', 'Cefixime PO 800mg'), ('AZM PO 1g', 'Azithromycin PO 1g'), ('AZM PO 2g', 'Azithromycin PO 2g'), ('Other', 'Other'), ('Unknown', 'Unknown')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Secondary_Antibiotic',
            field=models.CharField(choices=[('None', 'None'), ('AZM PO 1g', 'Azithromycin PO 1g'), ('AZM PO 2g', 'Azithromycin PO 2g'), ('DOX PO 100mg', 'Doxycycline PO 100mg'), ('TCY PO 500mg', 'Tetracycline PO 500mg'), ('Other', 'Other'), ('Unknown', 'Unknown')], default='None', max_length=100),
        ),
    ]
