# Generated by Django 5.2.3 on 2025-08-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_egasp_data_gender_identity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egasp_data',
            name='Abx_Use_None',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Abx_Use_Other',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Abx_Use_Prescribed',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Abx_Use_Self_Medicated',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='For_possible_WGS',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='n/a', max_length=101),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='GS_Negative',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Gs_Gram_neg_diplococcus',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Gs_NoGram_neg_diplococcus',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Gs_Not_performed',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Gs_Presence_Of_Pus_Cells',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Patient_Compliance_Antibiotics',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Presence_GN_Extracellular',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Presence_GN_Intracellular',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Prev_Test_Pos',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Result_Test_Cure_Followup',
            field=models.CharField(choices=[('', ''), ('Positive', 'Positive'), ('Negative', 'Negative'), ('No TOC Performed', 'No TOC Performed'), ('No Answer', 'No Answer'), ('N/A', 'N/A')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Result_Test_Cure_Initial',
            field=models.CharField(choices=[('', ''), ('Positive', 'Positive'), ('Negative', 'Negative'), ('No TOC Performed', 'No TOC Performed'), ('No Answer', 'No Answer'), ('N/A', 'N/A')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Retested_Mic',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Route_Dermal',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Route_Injectable_IV',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Route_Oral',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Route_Suppository',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='SB_Anal_Insertive',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='SB_Anal_Receptive',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='SB_Oral_Insertive',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='SB_Oral_Receptive',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='SB_Urethral',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='SB_Vaginal',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Sharing_of_Sex_Toys',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Sti_Anogenital_Warts',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Sti_Chlamydia',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Sti_Genital_Ulcer',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Sti_Hepatitis_B',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Sti_Hepatitis_C',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Sti_Herpes',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Sti_Hiv',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Sti_Lymphogranuloma',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Sti_Mycoplasma_genitalium',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Sti_NGI',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Sti_None',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Sti_Syphilis',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Sti_Trichomoniasis',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Symp_Discharge_Anus',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Symp_Discharge_Oropharyngeal',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Symp_Discharge_Urethra',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Symp_Discharge_Vagina',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Symp_No',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Symp_Pain_Lower_Abdomen',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Symp_Painful_Intercourse',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Symp_Painful_Urination',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Symp_Rectal_Pain',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Symp_Tender_Testicles',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No'), ('No Answer', 'No Answer'), ('n/a', 'n/a')], default='', max_length=100),
        ),
    ]
