# Generated by Django 5.2.3 on 2025-08-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_egasp_data_abx_use_none_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egasp_data',
            name='Egasp_Id',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='OtherDrugs_Route',
            field=models.CharField(choices=[('', ''), ('Oral', 'Oral'), ('Injectable(IV/IM)', 'Injectable(IV/IM)'), ('Dermal', 'Dermal'), ('Suppository', 'Suppository'), ('No Answer', 'No Answer'), ('N/A', 'N/A')], default='', max_length=100),
        ),
    ]
