# Generated by Django 5.2.3 on 2025-08-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_egasp_data_egasp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egasp_data',
            name='Specimen_Quality',
            field=models.CharField(choices=[('', ''), ('Acceptable', 'Acceptable'), ('Contaminated', 'Contaminated'), ('Non-viable', 'Non-viable'), ('Improperly Transported', 'Improperly Transported'), ('N/A', 'N/A')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Specimen_Quality_Cs',
            field=models.CharField(choices=[('', ''), ('Acceptable', 'Acceptable'), ('Contaminated', 'Contaminated'), ('Non-viable', 'Non-viable'), ('Improperly Transported', 'Improperly Transported'), ('N/A', 'N/A')], default='n/a', max_length=100),
        ),
    ]
