# Generated by Django 5.2.3 on 2025-08-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_egasp_data_specimen_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egasp_data',
            name='Growth_span_other',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
