# Generated by Django 5.2.3 on 2025-08-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_egasp_data_growth_span_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egasp_data',
            name='GS_Others',
            field=models.TextField(choices=[('n/a', 'n/a'), ('Negative', 'Negative'), ('Rare', 'Rare'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], default='', max_length=100),
        ),
    ]
