# Generated by Django 5.2.3 on 2025-08-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_egasp_data_gs_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='egasp_data',
            name='GS_Other_sp',
            field=models.CharField(choices=[('n/a', 'n/a'), ('Negative', 'Negative'), ('Rare', 'Rare'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='egasp_data',
            name='GS_Other_sp2',
            field=models.CharField(choices=[('n/a', 'n/a'), ('Negative', 'Negative'), ('Rare', 'Rare'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='egasp_data',
            name='GS_Other_sp3',
            field=models.CharField(choices=[('n/a', 'n/a'), ('Negative', 'Negative'), ('Rare', 'Rare'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='egasp_data',
            name='GS_Others2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='egasp_data',
            name='GS_Others3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='GS_Others',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
