# Generated by Django 5.2.3 on 2025-08-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_egasp_data_gs_other_sp_egasp_data_gs_other_sp2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egasp_data',
            name='Epithelial_Cells',
            field=models.CharField(choices=[('', ''), ('n/a', 'n/a'), ('Negative', 'Negative'), ('Rare', 'Rare'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='GS_Other_sp',
            field=models.CharField(choices=[('', ''), ('n/a', 'n/a'), ('Negative', 'Negative'), ('Rare', 'Rare'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='GS_Other_sp2',
            field=models.CharField(choices=[('', ''), ('n/a', 'n/a'), ('Negative', 'Negative'), ('Rare', 'Rare'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='GS_Other_sp3',
            field=models.CharField(choices=[('', ''), ('n/a', 'n/a'), ('Negative', 'Negative'), ('Rare', 'Rare'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='GS_Pus_Cells',
            field=models.CharField(choices=[('', ''), ('n/a', 'n/a'), ('Negative', 'Negative'), ('Rare', 'Rare'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Gram_Neg_Extracellular',
            field=models.CharField(choices=[('', ''), ('n/a', 'n/a'), ('Negative', 'Negative'), ('Rare', 'Rare'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Gram_Neg_Intracellular',
            field=models.CharField(choices=[('', ''), ('n/a', 'n/a'), ('Negative', 'Negative'), ('Rare', 'Rare'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], default='', max_length=100),
        ),
    ]
