# Generated by Django 5.2.3 on 2025-08-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_egasp_data_epithelial_cells_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egasp_data',
            name='Epithelial_Cells',
            field=models.CharField(choices=[('', ''), ('n/a', 'n/a'), ('Negative', 'Negative'), ('Rare', 'Rare'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], default='n/a', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='GS_Pus_Cells',
            field=models.CharField(choices=[('', ''), ('n/a', 'n/a'), ('Negative', 'Negative'), ('Rare', 'Rare'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], default='n/a', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Gram_Neg_Extracellular',
            field=models.CharField(choices=[('', ''), ('n/a', 'n/a'), ('Negative', 'Negative'), ('Rare', 'Rare'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], default='n/a', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Gram_Neg_Intracellular',
            field=models.CharField(choices=[('', ''), ('n/a', 'n/a'), ('Negative', 'Negative'), ('Rare', 'Rare'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], default='n/a', max_length=100),
        ),
    ]
