# Generated by Django 5.2.3 on 2025-08-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_egasp_data_permanent_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egasp_data',
            name='Permanent_City',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Permanent_Province',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
    ]
