# Generated by Django 5.2.3 on 2025-08-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_egasp_data_permanent_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egasp_data',
            name='Current_Country',
            field=models.CharField(blank=True, choices=[('Philippines', 'Philippines'), ('Other', 'Other')], default='Philippines', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Permanent_City',
            field=models.CharField(blank=True, choices=[('Philippines', 'Philippines'), ('Other', 'Other')], default='*None', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Permanent_Country',
            field=models.CharField(blank=True, choices=[('Philippines', 'Philippines'), ('Other', 'Other')], default='Philippines', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Permanent_Province',
            field=models.CharField(blank=True, choices=[('Philippines', 'Philippines'), ('Other', 'Other')], default='*None', max_length=100),
        ),
    ]
