# Generated by Django 5.2.3 on 2025-08-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_egasp_data_current_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egasp_data',
            name='Permanent_City',
            field=models.CharField(blank=True, default='*None', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Permanent_Province',
            field=models.CharField(blank=True, default='*None', max_length=100),
        ),
    ]
