# Generated by Django 5.2.3 on 2025-08-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_egasp_data_permanent_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egasp_data',
            name='Current_Country',
            field=models.CharField(choices=[('Philippines', 'Philippines'), ('Other', 'Other')], default='Philippines', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Permanent_Country',
            field=models.CharField(choices=[('Philippines', 'Philippines'), ('Other', 'Other')], default='Philippines', max_length=100),
        ),
    ]
