# Generated by Django 5.2.3 on 2025-08-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_egasp_data_current_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egasp_data',
            name='Current_City',
            field=models.CharField(default='*None', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Current_Province',
            field=models.CharField(default='*None', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Permanent_City',
            field=models.CharField(default='*None', max_length=100),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Permanent_Province',
            field=models.CharField(default='*None', max_length=100),
        ),
    ]
