# Generated by Django 5.2.3 on 2025-09-05 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_egasp_data_current_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic_Pers_Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pers_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Pers_License', models.CharField(blank=True, max_length=100, null=True)),
                ('Pers_Designation', models.CharField(blank=True, max_length=150, null=True)),
                ('Pers_Email', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator()])),
                ('Pers_Contact', models.CharField(blank=True, max_length=27, null=True)),
            ],
        ),
    ]
